---
driver:
  name: vagrant
  customize:
    audio: none

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.13.11 # 14.7.14 uses an old version of homebrew code, I think 14.9 has the fix?
  install_strategy: always # Install exact version we want, don't skip if there's any sort of install in the VM
  deprecations_as_errors: true

verifier:
  name: inspec
  reporter:
    - cli
    - junit:%{suite}-%{platform}-inspec.xml

platforms:

- name: ubuntu-16.04
  driver:
    customize:
      memory: 384
    run_list:
      - recipe[apt]
  attributes:
    java:
      jdk_version: 8

- name: macos-sierra
  driver:
    box: gobadiah/macos-sierra
    boot_timeout: 1200
  attributes:
    virtualization:
      system: vbox
      role: guest
    android:
      java_from_system: true

suites:

- name: ndk
  run_list:
    - recipe[test::ndk]
  attributes:
    android:
      set_environment_variables: true

- name: emulator
  run_list:
    - recipe[test::emulator]
  attributes:
    android:
      set_environment_variables: true

- name: default # covers sdk and component resources
  run_list:
    - recipe[test::_base]
    - recipe[android]
  attributes:
    android:
      set_environment_variables: true
      components:
        - platform-tools
        - build-tools;26.0.1
        - emulator
        - platforms;android-23
        - system-images;android-23;google_apis;armeabi-v7a
