---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 13.4.19
  chef_omnibus_url: http://omnitruck.chef.io/install.sh

verifier:
  name: inspec
  format: junit
  output: ./%{platform}_%{suite}_inspec.xml

platforms:

- name: ubuntu-12.04
  driver:
    customize:
      memory: 384
    run_list:
      - recipe[apt]

- name: ubuntu-14.04
  driver:
    customize:
      memory: 384
    run_list:
      - recipe[apt]

- name: ubuntu-16.04
  driver:
    customize:
      memory: 384
    run_list:
      - recipe[apt]

- name: centos-6.6
  driver:
    customize:
      memory: 512
    run_list:
      - recipe[yum]

- name: centos-7.1
  driver:
    customize:
      memory: 512
    run_list:
      - recipe[yum]

suites:

- name: wip # be prepared to work on https://github.com/gildegoma/chef-android-sdk/issues/14 (maven-android-sdk-deployer)
  run_list:
    - recipe[git]
    - recipe[maven]
    - recipe[android-sdk]
  attributes:
    android-sdk:
      owner: vagrant
      group: vagrant
    components:
      - build-tools;22.0.1
      - platforms;android-22
      - system-images;android-22;default;armeabi-v7a
    java:
      install_flavor: oracle
      jdk_version: 8
      oracle:
        accept_oracle_download_terms: true

- name: default
  run_list:
    - recipe[android-sdk]
  attributes:
    java:
      install_flavor: oracle
      jdk_version: 8
      oracle:
        accept_oracle_download_terms: true
    android-sdk:
      license:
        default_answer: y
      set_environment_variables: true
      components:
        - build-tools;22.0.1
        - platforms;android-22
        - system-images;android-22;default;armeabi-v7a
