---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13.4.19
  install_strategy: always # Install exact version we want, don't skip if there's any sort of install in the VM

verifier:
  name: inspec
  format: junit
  output: ./%{suite}-%{platform}-inspec.xml

platforms:

- name: ubuntu-16.04
  driver:
    customize:
      memory: 384
    run_list:
      - recipe[apt]
  attributes:
    java:
      install_flavor: oracle
      jdk_version: 8
      oracle:
        accept_oracle_download_terms: true

- name: macos-sierra
  driver:
    box: gobadiah/macos-sierra
    boot_timeout: 1200
  attributes:
    virtualization:
      system: vbox
      role: guest
    java:
      jdk_version: 8
    android-sdk:
      java_from_system: false

suites:

- name: ndk
  run_list:
    - recipe[test::ndk]

- name: emulator
  run_list:
    - recipe[test::emulator]

- name: default # covers sdk and component resources
  run_list:
    - recipe[android]
  attributes:
    android-sdk:
      license:
        default_answer: y
      set_environment_variables: true
      components:
        - platform-tools
        - build-tools;26.0.1
        - platforms;android-23
        - system-images;android-23;google_apis;armeabi-v7a
